all: sphere sphere_noconst sphere_global
sphere: sphere.cu
	nvcc sphere.cu -o sphere
sphere_noconst: sphere_noconst.cu
	nvcc sphere_noconst.cu -o sphere_noconst
sphere_global: sphere_global.cu
	nvcc sphere_global.cu -o sphere_global 
